### PR TITLE
Card

### PR DESCRIPTION
**Pull request by mohammed-sas**

### CODE REVIEW

**Comment by AnkurChunekar** [comment]
Hey, great work. i have one feedback if you can give some padding to the action buttons it can look more better, and you can remove unwanted comments, rest everything is fine. Approving for now.

**Review by AnkurChunekar — APPROVED** [review]

**Review by Abhijeet43 — APPROVED** [review]
Hey, mohammad it looks good....Just a suggestion just remove some blank comments in your css

**Comment by mohammed-sas** [comment]
> Hey, great work. i have one feedback if you can give some padding to the action buttons it can look more better, and you can remove unwanted comments, rest everything is fine. Approving for now.

thank you

**Comment by mohammed-sas** [comment]
> Hey, mohammad it looks good....Just a suggestion just remove some blank comments in your css

thank you

**Pull request merged**
