### PR TITLE
feat : snackbar 

### PR DESCRIPTION
**Pull request by mohammed-sas**

### CODE REVIEW

**Comment by Kevin-Solomon** [comment]
Hey mohammed , small suggestion could take a screen shot of the component add it to the description while committing.

**Comment by mohammed-sas** [comment]
> Hey mohammed , small suggestion could take a screen shot of the component add it to the description while committing.

thank you for the suggestion

**Comment by mohammed-sas** [comment]
Screen Shot 2022-01-31 at 1 07 25 PM
added the working snapshot

**Review by Abhijeet43 — APPROVED** [review]
Code is fine

**Review by Kevin-Solomon — APPROVED** [review]

**Pull request merged**
